### ISSUE TITLE
TextEditorComponent.measureDimensions is deprecated.

### ISSUE THREAD

**Issue by spawnsdf** [atom/about#56] opened 2017-05-17 04:11 UTC
Assigning editor 393's height explicitly via `position: 'absolute'` and an assigned `top` and `bottom` implicitly assigns the `autoHeight` property to false on the editor.
This behavior is deprecated and will not be supported in the future. Please explicitly assign `autoHeight` on this editor.
```
TextEditorComponent.measureDimensions (<embedded>:6897:26)
TextEditorComponent.becameVisible (<embedded>:6181:18)
TextEditorComponent.checkForVisibilityChange (<embedded>:6879:22)
atom-text-editor.attachedCallback (C:\Users\mushe\AppData\Local\atom\app-1.17.0\resources\app\src\text-editor-element.js:87:22)
<unknown> (<embedded>:1080:39)
```

**Comment by rsese** [comment] 2017-05-17 18:41
Thanks for reaching out!

This looks like a duplicate of https://github.com/atom/atom/issues/13653, please check out that issue for suggestions to get around the error /cc https://github.com/atom/atom/issues/13653#issuecomment-275877727.

Additionally, we require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Closed by rsese** 2017-05-17 18:41 UTC
